filebeat.modules:
- module: logstash
- module: nginx
  access:
    enabled: true
    var.paths: ["/usr/share/filebeat/logs/nginx/access.log*"]
  error:
    enabled: true
    var.paths: ["/usr/share/filebeat/logs/nginx/error.log*"]

filebeat.prospectors:
# files subject to normal php multiline support
- input_type: log
  paths:
    - /usr/share/filebeat/logs/my-errors.log
  encoding: latin1

  # Exclude lines. Has no effect with multilines
  # exclude_lines: ['^[ \t]+\r?$']
  # exclude_lines: ['^[ \t]+\r?$']
  fields:
    application_type: PHP
    application: AGNES-FPM

  fields_under_root: true
  #ignore_older: 24h
  document_type: php

  multiline:
  # - match lines not starting with "[...(somedigit)...]" to be appended after previous line
  multiline.pattern: '^\[[^\]]+[0-9][^\]]+\]'
  multiline.negate: true
  multiline.match: after
  multiline.max_lines: 1000
  # files subject to normal php multiline support
- input_type: log
  paths:
     - "/usr/share/filebeat/logs/system.log"
     - "/usr/share/filebeat/logs/exception.log"
  encoding: latin1

  # Exclude lines. Has no effect with multilines
  # exclude_lines: ['^[ \t]+\r?$']
  fields:
    application_type: magento
    application: AGNES

  fields_under_root: true
  #ignore_older: 24h
  document_type: agnes

  multiline:
  # - match lines not starting with "[...(somedigit)...]" to be appended after previous line
  multiline.pattern: '^\[[^\]]+[0-9][^\]]+\]'
  multiline.negate: true
  multiline.match: after
  multiline.max_lines: 1000   
    
#============================= Filebeat modules ===============================
filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["logstash:5044"]
logging.level: debug

logging.selectors: ["*"]
